version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: my-db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5555:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: